import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { supabase } from '@/lib/supabase';

type AgendaItem={kind:'event'|'academic';id:string;student_id?:string|null;title:string;category:string;starts_at?:string|null;status?:string;priority?:string;location?:string|null;sensitivity?:string};
type Context={students?:Array<{id:string;first_name:string;preferred_name?:string|null}>};
const labels:Record<string,string>={task:'Tarea',test:'Prueba',exam:'Examen',project:'Proyecto',material:'Material',school_event:'Colegio',school:'Colegio',study:'Estudio',sport:'Deporte',health:'Salud',social:'Actividad',family:'Familia',other:'Otro'};
const icons:Record<string,string>={task:'📝',test:'📚',exam:'📚',project:'🧩',material:'🎒',school_event:'🏫',school:'🏫',study:'🌱',sport:'⚽',health:'💛',social:'🎈',family:'🏡',other:'•'};
function keyFor(item:AgendaItem){if(!item.starts_at)return 'Sin fecha';return new Date(item.starts_at).toISOString().slice(0,10);}
function dateTitle(key:string){if(key==='Sin fecha')return key;const d=new Date(`${key}T12:00:00`);const today=new Date();const tomorrow=new Date();tomorrow.setDate(today.getDate()+1);if(key===today.toISOString().slice(0,10))return 'Hoy';if(key===tomorrow.toISOString().slice(0,10))return 'Mañana';return d.toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'});}

export default function Week(){
  const [items,setItems]=useState<AgendaItem[]>([]);const [context,setContext]=useState<Context>({});const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [busyId,setBusyId]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(false);const [{data:agenda,error:agendaError},{data:ctx,error:ctxError}]=await Promise.all([supabase.rpc('after_agenda',{p_days:8}),supabase.rpc('after_my_context')]);if(agendaError||ctxError){setError(true);setLoading(false);return;}setItems((agenda??[]) as AgendaItem[]);setContext((ctx??{}) as Context);setLoading(false);},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  const grouped=useMemo(()=>items.reduce<Record<string,AgendaItem[]>>((acc,item)=>{const key=keyFor(item);(acc[key]??=[]).push(item);return acc;},{}),[items]);
  const childName=(id?:string|null)=>{const child=context.students?.find(x=>x.id===id);return child?.preferred_name||child?.first_name||'Familia';};
  async function complete(item:AgendaItem){if(item.kind!=='academic'||busyId)return;setBusyId(item.id);const {error:rpcError}=await supabase.rpc('after_update_academic_status',{p_item_id:item.id,p_status:'done'});setBusyId(null);if(!rpcError)await load();}

  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.body} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}>
    <Text style={s.kicker}>LO QUE VIENE</Text><Text style={s.title}>Nuestra semana 🗓️</Text><Text style={s.copy}>Colegio, actividades y estudio en una sola vista. Sin llenar la pantalla de cosas que no necesitas.</Text>
    {loading&&!items.length?<View style={s.loading}><ActivityIndicator color="#F58B57"/><Text style={s.muted}>Ordenando la semana…</Text></View>:error?<View style={s.empty}><Text style={s.emptyTitle}>No pudimos cargar la semana.</Text><Text style={s.muted}>Vuelve a intentar cuando tengas conexión.</Text><Pressable onPress={()=>void load()} style={s.retry}><Text style={s.retryText}>Reintentar</Text></Pressable></View>:items.length?Object.entries(grouped).map(([day,dayItems])=><View key={day} style={s.dayBlock}><View style={s.dayPill}><Text style={s.day}>{dateTitle(day)}</Text></View><View style={s.rail}>{dayItems.map(item=><View key={`${item.kind}-${item.id}`} style={s.row}><View style={s.dot}/><View style={s.iconBubble}><Text>{icons[item.category]??'•'}</Text></View><View style={s.timeCol}><Text style={s.time}>{item.starts_at?new Date(item.starts_at).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}):'—'}</Text></View><View style={s.flex}><View style={s.topline}><Text style={s.type}>{labels[item.category]??item.category}</Text>{item.sensitivity==='private'?<Text style={s.private}>Privado</Text>:null}</View><Text style={s.itemTitle}>{item.title}</Text><Text style={s.meta}>{childName(item.student_id)}{item.location?` · ${item.location}`:''}{item.priority&&item.priority!=='normal'?` · prioridad ${item.priority}`:''}</Text></View>{item.kind==='academic'?<Pressable disabled={busyId===item.id} onPress={()=>void complete(item)} style={s.done}><Text style={s.doneText}>{busyId===item.id?'…':'✓'}</Text></Pressable>:null}</View>)}</View></View>):<View style={s.empty}><Text style={s.emptyEmoji}>🌿</Text><Text style={s.emptyTitle}>La semana está tranquila</Text><Text style={s.muted}>Cuando agregues tareas, pruebas o actividades aparecerán aquí.</Text></View>}
  </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF8F1'},body:{paddingHorizontal:18,paddingTop:18,paddingBottom:60},kicker:{fontSize:10.5,fontWeight:'900',letterSpacing:1.2,color:'#A17152'},title:{fontSize:33,lineHeight:38,fontWeight:'900',letterSpacing:-1,color:'#2B2926',marginTop:4},copy:{fontSize:15,lineHeight:22,color:'#71665C',marginTop:7,marginBottom:12},loading:{paddingVertical:40,alignItems:'center',gap:12},muted:{fontSize:13,lineHeight:19,color:'#81756A'},dayBlock:{marginTop:19},dayPill:{alignSelf:'flex-start',backgroundColor:'#FFF0E4',borderRadius:999,paddingHorizontal:11,paddingVertical:6,marginBottom:7},day:{fontSize:14,fontWeight:'900',textTransform:'capitalize',color:'#8B5C3D'},rail:{borderLeftWidth:1,borderLeftColor:'#E5D8CC',marginLeft:7,paddingLeft:15},row:{position:'relative',flexDirection:'row',alignItems:'center',gap:9,paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#EDE1D7'},dot:{position:'absolute',left:-20.5,width:10,height:10,borderRadius:5,backgroundColor:'#6F8F68',borderWidth:2,borderColor:'#FFF8F1'},iconBubble:{width:32,height:32,borderRadius:11,backgroundColor:'#FFFDF9',alignItems:'center',justifyContent:'center'},timeCol:{width:42},time:{fontSize:11.5,fontWeight:'900',color:'#806F61'},flex:{flex:1},topline:{flexDirection:'row',gap:7,alignItems:'center'},type:{fontSize:10,fontWeight:'900',letterSpacing:.4,textTransform:'uppercase',color:'#8B7A6C'},private:{fontSize:10,fontWeight:'800',color:'#8A6170'},itemTitle:{fontSize:14.5,fontWeight:'900',color:'#302D29',marginTop:3},meta:{fontSize:11.5,lineHeight:17,color:'#8A7E72',marginTop:3},done:{width:33,height:33,borderRadius:11,backgroundColor:'#EAF4E5',alignItems:'center',justifyContent:'center'},doneText:{fontSize:14,fontWeight:'900',color:'#567050'},empty:{marginTop:28,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E8DDD1',borderRadius:20,padding:18,gap:8},emptyEmoji:{fontSize:24},emptyTitle:{fontSize:18,fontWeight:'900',color:'#302D29'},retry:{alignSelf:'flex-start',backgroundColor:'#F58B57',borderRadius:11,paddingHorizontal:13,paddingVertical:9},retryText:{color:'#FFF',fontWeight:'900',fontSize:12}});