import { useEffect, useMemo, useState } from 'react';
import { Alert, KeyboardAvoidingView, Modal, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '@/lib/supabase';
import { FamilySignal } from '@/components/AfterGlyph';

type Member={id:string;display_name:string;role:string;is_me:boolean};
type Child={id:string;name:string;first_name?:string|null;preferred_name?:string|null;relationship_label?:string|null;school_name?:string|null;grade_level?:string|null};
type Responsibility={id:string;student_id:string|null;assigned_member_id:string|null;assigned_name:string|null;title:string;status:string};
type Workspace={family_id?:string;members?:Member[];students?:Child[];responsibilities?:Responsibility[]};
const statusLabel:Record<string,string>={unassigned:'Por definir',proposed:'Esperando respuesta',accepted:'En curso',declined:'No disponible',completed:'Listo'};
const relationOptions=['Hijo','Hija','Niño','Niña','Estudiante','Otro'];

function EmptySignal(){return <View style={s.emptySignal}><View style={s.emptyRail}/><View style={s.emptyDot}/><View style={s.emptyDotSoft}/></View>;}

export default function Family(){
  const {width}=useWindowDimensions();
  const compact=width<370;const wide=width>=720;
  const [workspace,setWorkspace]=useState<Workspace>({});const [busy,setBusy]=useState(false);const [title,setTitle]=useState('');
  const [childId,setChildId]=useState('');const [memberId,setMemberId]=useState('');const [inviteEmail,setInviteEmail]=useState('');const [inviteName,setInviteName]=useState('');const [showInvite,setShowInvite]=useState(false);
  const [editingId,setEditingId]=useState<string|null>(null);const [preferred,setPreferred]=useState('');const [relation,setRelation]=useState('Hijo');const [customRelation,setCustomRelation]=useState('');const [school,setSchool]=useState('');const [grade,setGrade]=useState('');
  const members=workspace.members??[];const children=workspace.students??[];const responsibilities=workspace.responsibilities??[];const me=useMemo(()=>members.find(m=>m.is_me),[members]);

  async function load(){const {data,error}=await supabase.rpc('after_family_workspace');if(!error){const ws=(data??{}) as Workspace;setWorkspace(ws);if(!childId&&ws.students?.[0])setChildId(ws.students[0].id);}}
  useEffect(()=>{void load();},[]);

  async function invite(){if(!workspace.family_id||!/^\S+@\S+\.\S+$/.test(inviteEmail.trim()))return Alert.alert('Correo inválido','Ingresa el correo de Google de la otra persona.');setBusy(true);const {error}=await supabase.rpc('after_invite_member',{p_family_id:workspace.family_id,p_email:inviteEmail.trim().toLowerCase(),p_display_name:inviteName.trim()||null,p_role:'parent'});setBusy(false);if(error)return Alert.alert('No pudimos invitar','Solo el propietario de la familia puede enviar invitaciones.');setInviteEmail('');setInviteName('');setShowInvite(false);Alert.alert('Invitación lista','Cuando esa persona ingrese con la misma cuenta Google podrá unirse.');}
  async function create(){if(!workspace.family_id||title.trim().length<2)return Alert.alert('Falta información','Escribe qué hay que coordinar.');setBusy(true);const {error}=await supabase.rpc('after_create_responsibility',{p_family_id:workspace.family_id,p_student_id:childId||null,p_title:title.trim(),p_assigned_member_id:memberId||null});setBusy(false);if(error)return Alert.alert('No pudimos guardar','Revisa tu sesión y los permisos familiares.');setTitle('');await load();}
  async function respond(id:string,action:'accepted'|'declined'|'completed'){setBusy(true);const {error}=await supabase.rpc('after_respond_responsibility',{p_responsibility_id:id,p_action:action});setBusy(false);if(error)return Alert.alert('No pudimos actualizar','Solo la persona asignada puede responder.');await load();}
  function startEdit(child:Child){setEditingId(child.id);setPreferred(child.preferred_name??'');const current=child.relationship_label||'Hijo';if(relationOptions.includes(current)){setRelation(current);setCustomRelation('');}else{setRelation('Otro');setCustomRelation(current);}setSchool(child.school_name??'');setGrade(child.grade_level??'');}
  async function saveChild(){if(!editingId)return;const relationship=relation==='Otro'?customRelation.trim():relation;if(!relationship)return Alert.alert('Falta un dato','Elige cómo quieres referirte a esta persona.');setBusy(true);const {error}=await supabase.rpc('after_update_student_identity',{p_student_id:editingId,p_preferred_name:preferred.trim()||null,p_relationship_label:relationship,p_school_name:school.trim()||null,p_grade_level:grade.trim()||null});setBusy(false);if(error)return Alert.alert('No pudimos guardar','Revisa los datos e intenta nuevamente.');setEditingId(null);await load();}
  async function logout(){const {error}=await supabase.auth.signOut();if(error)return Alert.alert('Error','No pudimos cerrar la sesión.');router.replace('/login');}

  return <SafeAreaView style={s.safe}>
    <ScrollView contentContainerStyle={[s.body,compact&&s.bodyCompact,wide&&s.bodyWide]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
      <View style={s.hero}>
        <View style={s.heroMark}><FamilySignal size={39}/></View>
        <Text style={s.eyebrow}>FAMILIA</Text>
        <Text style={[s.title,compact&&s.titleCompact]}>Que todos sepan qué sigue.</Text>
        <Text style={s.copy}>Coordina lo importante sin convertir la casa en una lista interminable de tareas.</Text>
      </View>

      <View style={s.peopleSection}>
        <View style={s.sectionHead}><View><Text style={s.heading}>A quienes acompañamos</Text><Text style={s.sectionCopy}>La información se adapta a cada persona.</Text></View><Text style={s.countLabel}>{children.length}</Text></View>
        <View style={s.peopleList}>{children.map(child=><Pressable accessibilityRole="button" accessibilityLabel={`Editar datos de ${child.name}`} key={child.id} onPress={()=>startEdit(child)} style={s.childRow}>
          <View style={s.personRail}/><View style={s.avatar}><Text style={s.avatarText}>{(child.name||'?').slice(0,1).toUpperCase()}</Text></View>
          <View style={s.flex}><Text style={s.childName}>{child.name}</Text><Text style={s.meta}>{child.relationship_label||'Niño/a'}{child.grade_level?` · ${child.grade_level}`:''}{child.school_name?` · ${child.school_name}`:''}</Text></View>
          <View style={s.editHint}><View style={s.editLine}/><View style={s.editLineShort}/></View>
        </Pressable>)}</View>
      </View>

      <View style={s.composer}>
        <Text style={s.composerKicker}>COORDINAR</Text><Text style={s.composerTitle}>¿Qué hay que resolver?</Text><Text style={s.muted}>Escríbelo como lo dirías en casa.</Text>
        <TextInput style={s.primaryInput} value={title} onChangeText={setTitle} maxLength={180} placeholder="Ej. Llevar a Vicente al dentista" placeholderTextColor="#A89C92" returnKeyType="done"/>
        <View style={s.choiceGroup}><Text style={s.label}>Para</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.horizontalChoices}>{children.map(child=><Pressable key={child.id} onPress={()=>setChildId(child.id)} style={[s.choice,childId===child.id&&s.choiceActive]}><View style={[s.choiceDot,childId===child.id&&s.choiceDotActive]}/><Text style={[s.choiceText,childId===child.id&&s.choiceTextActive]}>{child.name}</Text></Pressable>)}</ScrollView></View>
        <View style={s.choiceGroup}><Text style={s.label}>Responsable</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.horizontalChoices}><Pressable onPress={()=>setMemberId('')} style={[s.choice,memberId===''&&s.choiceActive]}><View style={[s.choiceDot,memberId===''&&s.choiceDotActive]}/><Text style={[s.choiceText,memberId===''&&s.choiceTextActive]}>Por definir</Text></Pressable>{members.map(m=><Pressable key={m.id} onPress={()=>setMemberId(m.id)} style={[s.choice,memberId===m.id&&s.choiceActive]}><View style={[s.choiceDot,memberId===m.id&&s.choiceDotActive]}/><Text style={[s.choiceText,memberId===m.id&&s.choiceTextActive]}>{m.display_name}{m.is_me?' · yo':''}</Text></Pressable>)}</ScrollView></View>
        <Pressable disabled={busy} onPress={()=>void create()} style={({pressed})=>[s.primaryButton,busy&&s.disabled,pressed&&!busy&&s.pressed]}><Text style={s.primaryButtonText}>{busy?'Guardando…':'Agregar pendiente'}</Text><View style={s.buttonTail}/></Pressable>
      </View>

      <View style={s.pendingSection}>
        <View style={s.sectionHead}><View><Text style={s.heading}>En marcha</Text><Text style={s.sectionCopy}>Solo lo que todavía necesita atención.</Text></View><Text style={s.countLabel}>{responsibilities.length}</Text></View>
        {responsibilities.length===0?<View style={s.empty}><EmptySignal/><View style={s.flex}><Text style={s.emptyTitle}>Todo está coordinado</Text><Text style={s.muted}>No hay nada pendiente por ahora.</Text></View></View>:<View style={s.itemList}>{responsibilities.map(r=>{const mine=Boolean(r.assigned_member_id&&r.assigned_member_id===me?.id);const child=children.find(c=>c.id===r.student_id);return <View key={r.id} style={s.item}>
          <View style={s.itemTrack}><View style={[s.itemNode,r.status==='completed'&&s.itemNodeDone]}/><View style={s.itemStem}/></View>
          <View style={s.flex}><Text style={s.itemTitle}>{r.title}</Text><Text style={s.meta}>{child?.name?`${child.name} · `:''}{r.assigned_name||'Sin responsable'}</Text><Text style={[s.status,r.status==='accepted'&&s.statusActive,r.status==='completed'&&s.statusDone]}>{statusLabel[r.status]||r.status}</Text></View>
          {mine&&r.status==='proposed'?<View style={s.itemActions}><Pressable onPress={()=>void respond(r.id,'accepted')} style={s.softButton}><Text style={s.softButtonText}>Me encargo</Text></Pressable><Pressable onPress={()=>void respond(r.id,'declined')}><Text style={s.decline}>No puedo</Text></Pressable></View>:null}
          {mine&&r.status==='accepted'?<Pressable onPress={()=>void respond(r.id,'completed')} style={s.softButton}><Text style={s.softButtonText}>Marcar listo</Text></Pressable>:null}
        </View>})}</View>}
      </View>

      {me?.role==='owner'?<View style={s.inviteSection}>
        <Pressable onPress={()=>setShowInvite(value=>!value)} style={s.inviteHeader}><View style={s.inviteMark}><View style={s.inviteNodeA}/><View style={s.inviteNodeB}/><View style={s.inviteLink}/></View><View style={s.flex}><Text style={s.heading}>Sumar a otro adulto</Text><Text style={s.sectionCopy}>{showInvite?'Completa los datos de la invitación.':'Comparte la coordinación sin compartir contraseñas.'}</Text></View><Text style={s.inviteAction}>{showInvite?'Cerrar':'Invitar'}</Text></Pressable>
        {showInvite?<View style={s.inviteForm}><TextInput style={s.input} value={inviteEmail} onChangeText={setInviteEmail} autoCapitalize="none" keyboardType="email-address" maxLength={254} placeholder="correo@gmail.com" placeholderTextColor="#A89C92"/><TextInput style={s.input} value={inviteName} onChangeText={setInviteName} maxLength={100} placeholder="Nombre (opcional)" placeholderTextColor="#A89C92"/><Pressable disabled={busy} onPress={()=>void invite()} style={[s.inviteButton,busy&&s.disabled]}><Text style={s.inviteButtonText}>Enviar invitación</Text></Pressable></View>:null}
      </View>:null}

      <Pressable onPress={()=>void logout()} style={s.logout}><Text style={s.logoutText}>Cerrar sesión</Text></Pressable>
    </ScrollView>

    <Modal visible={Boolean(editingId)} transparent animationType="slide" onRequestClose={()=>setEditingId(null)}>
      <KeyboardAvoidingView style={s.sheetHost} behavior={Platform.OS==='ios'?'padding':undefined}>
        <Pressable style={s.scrim} onPress={()=>setEditingId(null)}/>
        <View style={[s.sheet,wide&&s.sheetWide]}>
          <View style={s.sheetHandle}/><View style={s.sheetHeader}><View><Text style={s.heading}>Cómo habla tu familia</Text><Text style={s.sectionCopy}>Personaliza sin cambiar la identidad de la persona.</Text></View><Pressable onPress={()=>setEditingId(null)} style={s.closeButton}><View style={s.closeLineA}/><View style={s.closeLineB}/></Pressable></View>
          <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.sheetContent}>
            <TextInput style={s.input} value={preferred} onChangeText={setPreferred} maxLength={80} placeholder="Cómo le dicen en casa" placeholderTextColor="#A89C92"/>
            <Text style={s.label}>Cómo quieres referirte a esta persona</Text><View style={s.wrapChoices}>{relationOptions.map(value=><Pressable key={value} onPress={()=>setRelation(value)} style={[s.choice,relation===value&&s.choiceActive]}><View style={[s.choiceDot,relation===value&&s.choiceDotActive]}/><Text style={[s.choiceText,relation===value&&s.choiceTextActive]}>{value}</Text></Pressable>)}</View>
            {relation==='Otro'?<TextInput style={s.input} value={customRelation} onChangeText={setCustomRelation} maxLength={40} placeholder="Ej. Sobrino, nieta, ahijado…" placeholderTextColor="#A89C92"/>:null}
            <TextInput style={s.input} value={school} onChangeText={setSchool} maxLength={160} placeholder="Colegio (opcional)" placeholderTextColor="#A89C92"/>
            <TextInput style={s.input} value={grade} onChangeText={setGrade} maxLength={80} placeholder="Curso (opcional)" placeholderTextColor="#A89C92"/>
            <View style={s.sheetActions}><Pressable onPress={()=>setEditingId(null)} style={s.secondaryButton}><Text style={s.secondaryButtonText}>Cancelar</Text></Pressable><Pressable disabled={busy} onPress={()=>void saveChild()} style={[s.saveButton,busy&&s.disabled]}><Text style={s.saveButtonText}>{busy?'Guardando…':'Guardar cambios'}</Text></Pressable></View>
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </Modal>
  </SafeAreaView>;
}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:'#FFF9F3'},
  body:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:20,paddingTop:16,paddingBottom:36,gap:26},bodyCompact:{paddingHorizontal:14},bodyWide:{paddingHorizontal:30,paddingTop:26,gap:30},
  hero:{position:'relative',paddingRight:58,minHeight:112},heroMark:{position:'absolute',right:0,top:2,width:52,height:52,borderRadius:18,backgroundColor:'#EEF3E9',alignItems:'center',justifyContent:'center'},
  eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#A36C50',marginBottom:9},title:{fontSize:32,lineHeight:36,fontWeight:'900',letterSpacing:-.9,color:'#2C2926',maxWidth:520},titleCompact:{fontSize:28,lineHeight:32},copy:{fontSize:14.5,lineHeight:21,color:'#74695F',marginTop:10,maxWidth:540},
  peopleSection:{gap:12},sectionHead:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:16},heading:{fontSize:18,fontWeight:'900',letterSpacing:-.25,color:'#302D29'},sectionCopy:{fontSize:12.5,lineHeight:18,color:'#8B7E73',marginTop:3},countLabel:{fontSize:11,fontWeight:'900',color:'#9B8D82',paddingTop:4},peopleList:{gap:8},
  childRow:{minHeight:70,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E9DFD5',borderRadius:19,paddingVertical:11,paddingHorizontal:12,overflow:'hidden'},personRail:{position:'absolute',left:0,top:12,bottom:12,width:3,borderRadius:3,backgroundColor:'#F28B57'},avatar:{width:42,height:42,borderRadius:14,backgroundColor:'#EEF3E9',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:17,fontWeight:'900',color:'#4F6D55'},childName:{fontSize:16,fontWeight:'900',color:'#302D29'},flex:{flex:1},meta:{fontSize:11.5,lineHeight:17,color:'#8A7E72',marginTop:3},editHint:{width:24,height:24,alignItems:'flex-end',justifyContent:'center',gap:3},editLine:{width:16,height:2,borderRadius:2,backgroundColor:'#A9998C'},editLineShort:{width:9,height:2,borderRadius:2,backgroundColor:'#D1C4B9'},
  composer:{backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E8DDD2',borderRadius:26,padding:18,gap:13,shadowColor:'#3A2C22',shadowOpacity:.035,shadowRadius:18,shadowOffset:{width:0,height:8},elevation:1},composerKicker:{fontSize:9.5,fontWeight:'900',letterSpacing:1.4,color:'#A36C50'},composerTitle:{fontSize:21,fontWeight:'900',letterSpacing:-.4,color:'#302D29'},muted:{fontSize:12.5,lineHeight:18,color:'#81756A'},primaryInput:{backgroundColor:'#FFF9F3',borderWidth:1,borderColor:'#E9DDD2',borderRadius:17,paddingHorizontal:15,paddingVertical:14,fontSize:15.5,color:'#2B2926'},choiceGroup:{gap:7},label:{fontSize:11.5,fontWeight:'900',color:'#665B51',textTransform:'uppercase',letterSpacing:.7},horizontalChoices:{gap:8,paddingRight:18},wrapChoices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{minHeight:38,flexDirection:'row',alignItems:'center',gap:7,paddingVertical:8,paddingHorizontal:11,borderWidth:1,borderColor:'#E6DAD0',borderRadius:999,backgroundColor:'#FFF'},choiceActive:{backgroundColor:'#EFF4EB',borderColor:'#C9D7C3'},choiceDot:{width:7,height:7,borderRadius:4,backgroundColor:'#D9CCC1'},choiceDotActive:{backgroundColor:'#5E7C62'},choiceText:{fontSize:12.5,fontWeight:'800',color:'#6E6257'},choiceTextActive:{color:'#405A45'},primaryButton:{minHeight:52,borderRadius:16,backgroundColor:'#F28B57',alignItems:'center',justifyContent:'center',marginTop:2,overflow:'hidden'},primaryButtonText:{color:'#FFF',fontSize:14.5,fontWeight:'900'},buttonTail:{position:'absolute',right:-8,bottom:-14,width:62,height:32,borderRadius:32,backgroundColor:'rgba(255,255,255,.16)',transform:[{rotate:'-12deg'}]},pressed:{opacity:.9,transform:[{scale:.995}]},disabled:{opacity:.5},
  pendingSection:{gap:12},itemList:{gap:0,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E9DFD5',borderRadius:22,paddingHorizontal:14},item:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#F0E8E1'},itemTrack:{width:16,alignSelf:'stretch',alignItems:'center'},itemNode:{width:8,height:8,borderRadius:4,backgroundColor:'#F28B57',marginTop:5},itemNodeDone:{backgroundColor:'#6E8A6D'},itemStem:{width:2,flex:1,minHeight:18,backgroundColor:'#E8DED5',marginTop:4,borderRadius:2},itemTitle:{fontSize:14.5,fontWeight:'900',color:'#302D29'},status:{fontSize:10.5,fontWeight:'900',color:'#A36C50',marginTop:5,textTransform:'uppercase',letterSpacing:.5},statusActive:{color:'#5F7D63'},statusDone:{color:'#7B7067'},itemActions:{alignItems:'flex-end',gap:7},softButton:{backgroundColor:'#EEF4E9',borderRadius:11,paddingVertical:8,paddingHorizontal:10},softButtonText:{fontSize:11.5,fontWeight:'900',color:'#56705A'},decline:{fontSize:11.5,fontWeight:'900',color:'#A65E55'},empty:{minHeight:86,flexDirection:'row',alignItems:'center',gap:13,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E9DFD5',borderRadius:22,padding:16},emptySignal:{width:40,height:40,borderRadius:14,backgroundColor:'#F4F0EA',position:'relative'},emptyRail:{position:'absolute',left:10,top:19,width:20,height:2,borderRadius:2,backgroundColor:'#C7B8AD'},emptyDot:{position:'absolute',left:8,top:16,width:8,height:8,borderRadius:4,backgroundColor:'#6F8B6E'},emptyDotSoft:{position:'absolute',right:7,top:11,width:6,height:6,borderRadius:3,backgroundColor:'#F2A37C'},emptyTitle:{fontSize:14.5,fontWeight:'900',color:'#302D29'},
  inviteSection:{backgroundColor:'#FFF1E6',borderRadius:24,padding:15,gap:13},inviteHeader:{flexDirection:'row',alignItems:'center',gap:11},inviteMark:{width:42,height:42,borderRadius:14,backgroundColor:'#FFF9F3',position:'relative'},inviteNodeA:{position:'absolute',left:9,top:10,width:9,height:9,borderWidth:2,borderColor:'#6F8B6E',borderRadius:5},inviteNodeB:{position:'absolute',right:8,bottom:9,width:9,height:9,borderRadius:5,backgroundColor:'#F28B57'},inviteLink:{position:'absolute',left:15,top:20,width:14,height:2,borderRadius:2,backgroundColor:'#BDAA9A',transform:[{rotate:'28deg'}]},inviteAction:{fontSize:12,fontWeight:'900',color:'#A35F3C'},inviteForm:{gap:10,paddingTop:2},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E7DAD0',borderRadius:15,paddingHorizontal:14,paddingVertical:13,fontSize:15,color:'#2B2926'},inviteButton:{minHeight:48,backgroundColor:'#7A6652',borderRadius:15,alignItems:'center',justifyContent:'center'},inviteButtonText:{color:'#FFF',fontWeight:'900'},
  logout:{alignSelf:'center',paddingVertical:12,paddingHorizontal:18},logoutText:{fontSize:12.5,fontWeight:'800',color:'#9A8374'},
  sheetHost:{flex:1,justifyContent:'flex-end'},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(39,31,26,.28)'},sheet:{width:'100%',maxHeight:'86%',backgroundColor:'#FFF9F3',borderTopLeftRadius:28,borderTopRightRadius:28,paddingTop:10,paddingHorizontal:18,paddingBottom:22,shadowColor:'#2B2926',shadowOpacity:.15,shadowRadius:22,shadowOffset:{width:0,height:-6},elevation:18},sheetWide:{width:'72%',maxWidth:620,alignSelf:'center',borderRadius:28,marginBottom:24},sheetHandle:{width:42,height:4,borderRadius:4,backgroundColor:'#D9CEC4',alignSelf:'center',marginBottom:14},sheetHeader:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:12},closeButton:{width:36,height:36,borderRadius:12,backgroundColor:'#F1EAE4',alignItems:'center',justifyContent:'center'},closeLineA:{position:'absolute',width:15,height:2,borderRadius:2,backgroundColor:'#7E7065',transform:[{rotate:'45deg'}]},closeLineB:{position:'absolute',width:15,height:2,borderRadius:2,backgroundColor:'#7E7065',transform:[{rotate:'-45deg'}]},sheetContent:{gap:12,paddingTop:18,paddingBottom:10},sheetActions:{flexDirection:'row',gap:10,marginTop:4},secondaryButton:{flex:1,minHeight:48,borderWidth:1,borderColor:'#DED1C6',borderRadius:14,alignItems:'center',justifyContent:'center'},secondaryButtonText:{fontSize:12.5,fontWeight:'900',color:'#796D63'},saveButton:{flex:1.5,minHeight:48,backgroundColor:'#668064',borderRadius:14,alignItems:'center',justifyContent:'center'},saveButtonText:{fontSize:12.5,fontWeight:'900',color:'#FFF'}
});