import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { supabase } from '@/lib/supabase';

type FlowItem={kind:'academic'|'event';id:string;student_id?:string|null;title:string;category:string;starts_at?:string|null;status?:string;priority?:string;subject?:string};
type Overview={overdue:FlowItem[];today:FlowItem[];tomorrow:FlowItem[];week:FlowItem[]};
type Member={id:string;display_name:string;role:string;is_me:boolean};
type Responsibility={id:string;student_id:string|null;assigned_member_id:string|null;assigned_name:string|null;title:string;status:string};
type Workspace={members?:Member[];responsibilities?:Responsibility[]};
const statusLabel:Record<string,string>={unassigned:'Por asignar',proposed:'Esperando respuesta',accepted:'En curso',declined:'Rechazada',completed:'Lista'};
const academicLabel:Record<string,string>={task:'Tarea',test:'Prueba',exam:'Examen',project:'Proyecto',material:'Material',school_event:'Colegio'};
const academicIcon:Record<string,string>={task:'📝',test:'📚',exam:'📚',project:'🧩',material:'🎒',school_event:'🏫'};

export default function Pending(){
  const [overview,setOverview]=useState<Overview>({overdue:[],today:[],tomorrow:[],week:[]});const [workspace,setWorkspace]=useState<Workspace>({});const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [busyId,setBusyId]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(false);const [{data:flow,error:flowError},{data:family,error:familyError}]=await Promise.all([supabase.rpc('after_school_overview'),supabase.rpc('after_family_workspace')]);if(flowError||familyError){setError(true);setLoading(false);return;}setOverview((flow??{overdue:[],today:[],tomorrow:[],week:[]}) as Overview);setWorkspace((family??{}) as Workspace);setLoading(false);},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
  const academic=[...overview.overdue,...overview.today,...overview.tomorrow,...overview.week].filter((item,index,array)=>item.kind==='academic'&&array.findIndex(x=>x.id===item.id)===index);const me=workspace.members?.find(x=>x.is_me);const responsibilities=(workspace.responsibilities??[]).filter(x=>x.status!=='completed');
  async function completeAcademic(id:string){if(busyId)return;setBusyId(id);const {error:rpcError}=await supabase.rpc('after_update_academic_status',{p_item_id:id,p_status:'done'});setBusyId(null);if(!rpcError)await load();}
  async function respond(id:string,action:'accepted'|'declined'|'completed'){if(busyId)return;setBusyId(id);const {error:rpcError}=await supabase.rpc('after_respond_responsibility',{p_responsibility_id:id,p_action:action});setBusyId(null);if(!rpcError)await load();}

  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.body} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}>
    <Text style={s.kicker}>LO QUE FALTA</Text><Text style={s.title}>Pendientes, sin enredos ✓</Text><Text style={s.copy}>Lo del colegio y lo de casa que todavía necesita una pequeña acción.</Text>
    {loading&&!academic.length&&!responsibilities.length?<View style={s.loading}><ActivityIndicator color="#F58B57"/><Text style={s.muted}>Revisando pendientes…</Text></View>:error?<View style={s.empty}><Text style={s.emptyTitle}>No pudimos cargar los pendientes.</Text><Pressable onPress={()=>void load()} style={s.primary}><Text style={s.primaryText}>Reintentar</Text></Pressable></View>:<>
      <View style={s.schoolCard}><View style={s.head}><View><Text style={s.cardKicker}>📚 COLEGIO</Text><Text style={s.sectionTitle}>Por hacer</Text></View><Pressable onPress={()=>router.push('/(app)/estudio')}><Text style={s.link}>Preparar estudio</Text></Pressable></View>{academic.length?academic.map(item=><View key={item.id} style={s.item}><View style={s.iconBubble}><Text>{academicIcon[item.category]??'📝'}</Text></View><View style={s.flex}><Text style={s.type}>{academicLabel[item.category]??item.category}{item.subject?` · ${item.subject}`:''}</Text><Text style={s.itemTitle}>{item.title}</Text><Text style={s.meta}>{item.starts_at?new Date(item.starts_at).toLocaleString('es-CL',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Sin fecha'}{item.priority&&item.priority!=='normal'?` · prioridad ${item.priority}`:''}</Text></View><Pressable disabled={busyId===item.id} onPress={()=>void completeAcademic(item.id)} style={s.done}><Text style={s.doneText}>{busyId===item.id?'…':'✓'}</Text></Pressable></View>):<View style={s.emptyRow}><Text style={s.emptyEmoji}>🌿</Text><Text style={s.muted}>No hay tareas escolares pendientes en los próximos días.</Text></View>}</View>

      <View style={s.familyCard}><View style={s.head}><View><Text style={s.cardKicker}>🏡 FAMILIA</Text><Text style={s.sectionTitle}>Por coordinar</Text></View><Pressable onPress={()=>router.push('/(app)/familia')}><Text style={s.link}>Coordinar</Text></Pressable></View>{responsibilities.length?responsibilities.map(item=>{const mine=Boolean(item.assigned_member_id&&item.assigned_member_id===me?.id);return <View key={item.id} style={s.item}><View style={s.iconBubbleFamily}><Text>🏡</Text></View><View style={s.flex}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.meta}>{item.assigned_name||'Sin responsable'} · {statusLabel[item.status]||item.status}</Text></View>{mine&&item.status==='proposed'?<View style={s.actions}><Pressable disabled={busyId===item.id} onPress={()=>void respond(item.id,'accepted')} style={s.softButton}><Text style={s.softButtonText}>Me encargo</Text></Pressable><Pressable disabled={busyId===item.id} onPress={()=>void respond(item.id,'declined')}><Text style={s.reject}>No puedo</Text></Pressable></View>:null}{mine&&item.status==='accepted'?<Pressable disabled={busyId===item.id} onPress={()=>void respond(item.id,'completed')} style={s.done}><Text style={s.doneText}>✓</Text></Pressable>:null}</View>}):<View style={s.emptyRow}><Text style={s.emptyEmoji}>✨</Text><Text style={s.muted}>No hay responsabilidades familiares pendientes.</Text></View>}</View>
    </>}
  </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF8F1'},body:{paddingHorizontal:18,paddingTop:18,paddingBottom:60,gap:18},kicker:{fontSize:10.5,fontWeight:'900',letterSpacing:1.2,color:'#A17152'},title:{fontSize:32,lineHeight:37,fontWeight:'900',letterSpacing:-.9,color:'#2B2926'},copy:{fontSize:15,lineHeight:22,color:'#71665C'},loading:{paddingVertical:38,alignItems:'center',gap:11},muted:{fontSize:12.5,lineHeight:18,color:'#81756A'},schoolCard:{backgroundColor:'#EEF4EA',borderRadius:23,padding:16,gap:3},familyCard:{backgroundColor:'#FFF0E4',borderRadius:23,padding:16,gap:3},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:5},cardKicker:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#7B8F76'},sectionTitle:{fontSize:20,fontWeight:'900',color:'#302D29',marginTop:2},link:{fontSize:11.5,fontWeight:'900',color:'#5D7758'},item:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:11,borderTopWidth:1,borderTopColor:'rgba(130,110,90,.12)'},iconBubble:{width:34,height:34,borderRadius:12,backgroundColor:'#FFFDF9',alignItems:'center',justifyContent:'center'},iconBubbleFamily:{width:34,height:34,borderRadius:12,backgroundColor:'#FFF8F1',alignItems:'center',justifyContent:'center'},flex:{flex:1},type:{fontSize:10,fontWeight:'900',letterSpacing:.4,textTransform:'uppercase',color:'#7D8C78'},itemTitle:{fontSize:14.5,fontWeight:'900',color:'#302D29',marginTop:2},meta:{fontSize:11.5,lineHeight:17,color:'#8A7E72',marginTop:3},done:{width:34,height:34,borderRadius:12,backgroundColor:'#FFFDF9',alignItems:'center',justifyContent:'center'},doneText:{fontSize:14,fontWeight:'900',color:'#567050'},actions:{alignItems:'flex-end',gap:6},softButton:{backgroundColor:'#FFFDF9',borderRadius:10,paddingVertical:8,paddingHorizontal:9},softButtonText:{fontSize:11,fontWeight:'900',color:'#6F655B'},reject:{fontSize:11,fontWeight:'900',color:'#A65E55'},empty:{backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E8DDD1',borderRadius:20,padding:18,gap:10},emptyTitle:{fontSize:18,fontWeight:'900',color:'#302D29'},emptyRow:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:10},emptyEmoji:{fontSize:20},primary:{alignSelf:'flex-start',backgroundColor:'#F58B57',borderRadius:11,paddingVertical:9,paddingHorizontal:13},primaryText:{fontSize:12,fontWeight:'900',color:'#FFF'}});