import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ScheduleField } from '@/components/ScheduleField';
import { getFamilyWorkspace, getResponsibility, respondResponsibility, updateResponsibility, type FamilyWorkspace, type Responsibility } from '@/lib/coordination';

function firstParam(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value;}

export default function ResponsibilityEditor(){
  const params=useLocalSearchParams<{id?:string|string[]}>();const id=firstParam(params.id)??'';
  const [workspace,setWorkspace]=useState<FamilyWorkspace>({});const [record,setRecord]=useState<Responsibility|null>(null);
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [loadError,setLoadError]=useState(false);
  const [title,setTitle]=useState('');const [studentId,setStudentId]=useState('');const [memberId,setMemberId]=useState('');const [dueAt,setDueAt]=useState(new Date());const [contextText,setContextText]=useState('');

  useEffect(()=>{let active=true;async function load(){if(!id){setLoadError(true);setLoading(false);return;}setLoading(true);try{const [nextWorkspace,nextRecord]=await Promise.all([getFamilyWorkspace(),getResponsibility(id)]);if(!active)return;setWorkspace(nextWorkspace);setRecord(nextRecord);setTitle(nextRecord.title);setStudentId(nextRecord.student_id??'');setMemberId(nextRecord.assigned_member_id??'');setContextText(nextRecord.context_text??'');const parsed=nextRecord.due_at?new Date(nextRecord.due_at):new Date();setDueAt(Number.isNaN(parsed.getTime())?new Date():parsed);}catch{if(active)setLoadError(true);}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[id]);

  const members=workspace.members??[];const students=workspace.students??[];const me=useMemo(()=>members.find(member=>member.is_me),[members]);const mine=Boolean(record?.assigned_member_id&&record.assigned_member_id===me?.id);
  const canSave=Boolean(record&&title.trim().length>=2&&!busy&&record.status!=='completed');

  async function save(){if(!record||!canSave)return;setBusy(true);try{await updateResponsibility(record.id,{studentId:studentId||null,title,assignedMemberId:memberId||null,dueAt,contextText});Alert.alert('Actualizado','La responsabilidad ya refleja el nuevo responsable y plazo.');router.replace('/(app)/familia');}catch(error){Alert.alert('No pudimos actualizar',error instanceof Error?error.message:'Vuelve a intentar.');}finally{setBusy(false);}}

  async function respond(action:'accepted'|'declined'|'completed'){if(!record||busy)return;setBusy(true);try{await respondResponsibility(record.id,action);router.replace('/(app)/familia');}catch(error){Alert.alert('No pudimos actualizar',error instanceof Error?error.message:'Vuelve a intentar.');}finally{setBusy(false);}}

  if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator color="#F58B57"/><Text style={s.muted}>Abriendo responsabilidad…</Text></View></SafeAreaView>;
  if(loadError||!record)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.errorTitle}>No pudimos abrirla</Text><Text style={s.muted}>Puede haber cambiado o tu conexión puede estar interrumpida.</Text><Pressable onPress={()=>router.back()} style={s.primary}><Text style={s.primaryText}>Volver</Text></Pressable></View></SafeAreaView>;

  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.body} keyboardShouldPersistTaps="handled">
    <Pressable accessibilityRole="button" onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹ Volver</Text></Pressable>
    <Text style={s.kicker}>RESPONSABILIDAD</Text><Text style={s.title}>Ajusta quién, qué y cuándo.</Text><Text style={s.copy}>Reasignar o cambiar el plazo no obliga a recrear el pendiente.</Text>

    <View style={s.statusBox}><Text style={s.statusLabel}>Estado</Text><Text style={s.statusValue}>{record.status==='unassigned'?'Por definir':record.status==='proposed'?'Esperando respuesta':record.status==='accepted'?'En curso':record.status==='declined'?'No disponible':'Listo'}</Text>{record.assigned_name?<Text style={s.statusMeta}>{record.assigned_name}</Text>:null}</View>

    <View style={s.group}><Text style={s.label}>Qué hay que resolver</Text><TextInput value={title} onChangeText={setTitle} maxLength={180} style={s.input}/></View>
    <View style={s.group}><Text style={s.label}>Para</Text><View style={s.chips}><Pressable onPress={()=>setStudentId('')} style={[s.chip,!studentId&&s.chipActive]}><Text style={[s.chipText,!studentId&&s.chipTextActive]}>Familia</Text></Pressable>{students.map(student=>{const selected=studentId===student.id;return <Pressable key={student.id} onPress={()=>setStudentId(student.id)} style={[s.chip,selected&&s.chipActive]}><Text style={[s.chipText,selected&&s.chipTextActive]}>{student.name}</Text></Pressable>;})}</View></View>
    <View style={s.group}><Text style={s.label}>Responsable</Text><View style={s.chips}><Pressable onPress={()=>setMemberId('')} style={[s.chip,!memberId&&s.chipActive]}><Text style={[s.chipText,!memberId&&s.chipTextActive]}>Por definir</Text></Pressable>{members.map(member=>{const selected=memberId===member.id;return <Pressable key={member.id} onPress={()=>setMemberId(member.id)} style={[s.chip,selected&&s.chipActive]}><Text style={[s.chipText,selected&&s.chipTextActive]}>{member.display_name}{member.is_me?' · yo':''}</Text></Pressable>;})}</View></View>
    <ScheduleField value={dueAt} onChange={setDueAt} label="Fecha límite"/>
    <View style={s.group}><Text style={s.label}>Contexto</Text><TextInput value={contextText} onChangeText={setContextText} maxLength={1000} multiline placeholder="Información útil para poder resolverlo" placeholderTextColor="#A69A90" style={[s.input,s.note]}/></View>

    {record.status!=='completed'?<Pressable disabled={!canSave} onPress={()=>void save()} style={[s.save,!canSave&&s.disabled]}><Text style={s.saveText}>{busy?'Guardando…':'Guardar cambios'}</Text></Pressable>:null}
    {mine&&record.status==='proposed'?<View style={s.actions}><Pressable disabled={busy} onPress={()=>void respond('accepted')} style={s.accept}><Text style={s.acceptText}>Me encargo</Text></Pressable><Pressable disabled={busy} onPress={()=>void respond('declined')} style={s.decline}><Text style={s.declineText}>No puedo</Text></Pressable></View>:null}
    {mine&&record.status==='accepted'?<Pressable disabled={busy} onPress={()=>void respond('completed')} style={s.complete}><Text style={s.completeText}>✓ Marcar listo</Text></Pressable>:null}
  </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF8F1'},body:{paddingHorizontal:18,paddingTop:12,paddingBottom:70,gap:18},back:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingRight:12},backText:{fontSize:14,fontWeight:'900',color:'#6B655D'},kicker:{fontSize:10.5,fontWeight:'900',letterSpacing:1.2,color:'#9A765D'},title:{fontSize:30,lineHeight:35,fontWeight:'900',color:'#2B2926',marginTop:-11},copy:{fontSize:14.5,lineHeight:21,color:'#756B62',marginTop:-10},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:28},muted:{fontSize:13,lineHeight:19,color:'#81756A',textAlign:'center'},errorTitle:{fontSize:19,fontWeight:'900',color:'#302D29'},primary:{minHeight:44,justifyContent:'center',backgroundColor:'#597657',borderRadius:12,paddingHorizontal:15},primaryText:{color:'#FFF',fontWeight:'900'},statusBox:{backgroundColor:'#EEF4EA',borderRadius:17,padding:14,gap:3},statusLabel:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#71806D'},statusValue:{fontSize:16,fontWeight:'900',color:'#40523E'},statusMeta:{fontSize:12,color:'#748070'},group:{gap:8},label:{fontSize:13,fontWeight:'800',color:'#5E5A52'},input:{minHeight:50,borderRadius:15,borderWidth:1,borderColor:'#E7DCD1',backgroundColor:'#FFFDF9',paddingHorizontal:14,fontSize:15,color:'#2B2926'},note:{minHeight:90,paddingTop:13,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:44,justifyContent:'center',paddingHorizontal:14,borderRadius:999,borderWidth:1,borderColor:'#E7DCD1',backgroundColor:'#FFFDF9'},chipActive:{backgroundColor:'#597657',borderColor:'#597657'},chipText:{fontSize:13,fontWeight:'900',color:'#655B52'},chipTextActive:{color:'#FFF'},save:{minHeight:54,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#597657'},saveText:{color:'#FFF',fontSize:15,fontWeight:'900'},disabled:{opacity:.45},actions:{flexDirection:'row',gap:10},accept:{flex:1,minHeight:50,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#EAF4E5'},acceptText:{fontSize:13,fontWeight:'900',color:'#50704D'},decline:{flex:1,minHeight:50,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#FBE4E0'},declineText:{fontSize:13,fontWeight:'900',color:'#A94E45'},complete:{minHeight:52,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#EAF4E5'},completeText:{fontSize:14,fontWeight:'900',color:'#50704D'}});