import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { z } from 'zod';
import { supabase } from '@/lib/supabase';

const familySchema=z.object({familyName:z.string().trim().min(2).max(100),displayName:z.string().trim().min(2).max(100)});
const childSchema=z.object({firstName:z.string().trim().min(1).max(80),preferredName:z.string().trim().max(80),schoolName:z.string().trim().max(160),gradeLevel:z.string().trim().max(80),relationshipLabel:z.string().trim().min(1).max(40)});
type Invitation={id:string;family_id:string;family_name:string;role:string;display_name:string|null;expires_at:string};
type FamilyContext={family_id?:string|null;family_name?:string|null;display_name?:string|null;students?:Array<{id?:string|null}>|null};
type AccessState={state?:'active'|'paused'|'closed'|'none'};
const relationshipOptions=['Hijo','Hija','Niño','Niña','Estudiante','Otro'];

function getFamilyContext(context:unknown):FamilyContext|null{if(Array.isArray(context)){const row=context.find((item)=>Boolean(item&&typeof item==='object'&&'family_id' in item&&item.family_id));return row&&typeof row==='object'?(row as FamilyContext):null;}return context&&typeof context==='object'?(context as FamilyContext):null;}

export default function Onboarding(){
  const [familyId,setFamilyId]=useState<string|null>(null);const [familyName,setFamilyName]=useState('');const [displayName,setDisplayName]=useState('');
  const [firstName,setFirstName]=useState('');const [preferredName,setPreferredName]=useState('');const [schoolName,setSchoolName]=useState('');const [gradeLevel,setGradeLevel]=useState('');
  const [relationshipChoice,setRelationshipChoice]=useState('Hijo');const [customRelationship,setCustomRelationship]=useState('');
  const [invitations,setInvitations]=useState<Invitation[]>([]);const [busy,setBusy]=useState(false);const [loadingContext,setLoadingContext]=useState(true);const [accessCheckFailed,setAccessCheckFailed]=useState(false);

  useEffect(()=>{let active=true;async function load(){const [{data:accessData,error:accessError},{data:context,error:contextError},{data:inviteData}]=await Promise.all([supabase.rpc('after_my_access_state'),supabase.rpc('after_my_context'),supabase.rpc('after_my_invitations')]);if(!active)return;if(accessError||contextError){setAccessCheckFailed(true);setLoadingContext(false);return;}const access=(accessData??{}) as AccessState;if(access.state==='paused'||access.state==='closed'){router.replace('/access-paused');return;}const family=getFamilyContext(context);const hasChild=Boolean(family?.students?.some((child)=>Boolean(child?.id)));if(family?.family_id&&hasChild){router.replace('/(app)');return;}if(family?.family_id){setFamilyId(String(family.family_id));setFamilyName(family.family_name??'');setDisplayName(family.display_name??'');}setInvitations((inviteData??[]) as Invitation[]);setLoadingContext(false);}void load();return()=>{active=false;};},[]);

  async function acceptInvitation(invitation:Invitation){setBusy(true);const {error}=await supabase.rpc('after_accept_invitation',{p_invitation_id:invitation.id,p_display_name:invitation.display_name});setBusy(false);if(error)return Alert.alert('No pudimos aceptar la invitación','Puede haber expirado o corresponder a otra cuenta de Google.');router.replace('/');}
  async function createFamily(){const parsed=familySchema.safeParse({familyName,displayName});if(!parsed.success)return Alert.alert('Revisa los datos','Completa el nombre de la familia y cómo quieres aparecer en After.');setBusy(true);const {data,error}=await supabase.rpc('after_create_family',{p_family_name:parsed.data.familyName,p_display_name:parsed.data.displayName});setBusy(false);if(error||!data)return Alert.alert('No pudimos crear la familia','Revisa tu sesión e intenta nuevamente.');setFamilyId(String(data));}
  async function createChild(){if(!familyId)return;const relationshipLabel=relationshipChoice==='Otro'?customRelationship.trim():relationshipChoice;const parsed=childSchema.safeParse({firstName,preferredName,schoolName,gradeLevel,relationshipLabel});if(!parsed.success)return Alert.alert('Revisa los datos','Ingresa el nombre y cómo quieres referirte a esta persona en After.');setBusy(true);const {error}=await supabase.rpc('after_create_student',{p_family_id:familyId,p_first_name:parsed.data.firstName,p_preferred_name:parsed.data.preferredName||null,p_birth_date:null,p_school_name:parsed.data.schoolName||null,p_grade_level:parsed.data.gradeLevel||null,p_relationship_label:parsed.data.relationshipLabel});setBusy(false);if(error)return Alert.alert('No pudimos guardar','Revisa los datos e intenta nuevamente.');router.replace('/');}

  if(loadingContext)return <SafeAreaView style={s.safe}><View style={s.loading}><Text style={s.emoji}>🏡</Text><Text style={s.copy}>Preparando tu espacio familiar…</Text></View></SafeAreaView>;
  if(accessCheckFailed)return <SafeAreaView style={s.safe}><View style={s.loading}><Text style={s.title}>No pudimos verificar tu acceso.</Text><Text style={s.copy}>Tu sesión sigue protegida. Revisa tu conexión e intenta nuevamente.</Text><Pressable onPress={()=>router.replace('/')} style={s.button}><Text style={s.buttonText}>Reintentar</Text></Pressable></View></SafeAreaView>;

  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled">
    <View style={s.brandRow}><View style={s.logo}><Text style={s.logoText}>A</Text></View><View><Text style={s.brand}>Lestra After</Text><Text style={s.brandSub}>La vida familiar, un poco más liviana.</Text></View></View>
    {!familyId&&invitations.length>0?<View style={s.inviteBox}><Text style={s.step}>INVITACIÓN</Text><Text style={s.inviteTitle}>Tu familia ya te está esperando</Text>{invitations.map(inv=><View key={inv.id} style={s.inviteRow}><View style={{flex:1}}><Text style={s.inviteFamily}>{inv.family_name}</Text><Text style={s.copy}>Te invitaron como {inv.role==='parent'?'adulto responsable':'tutor'}.</Text></View><Pressable disabled={busy} onPress={()=>acceptInvitation(inv)} style={s.smallButton}><Text style={s.buttonText}>Unirme</Text></Pressable></View>)}</View>:null}
    {!familyId?<View style={s.card}><Text style={s.step}>PASO 1 DE 2</Text><Text style={s.title}>Primero, creemos tu hogar en After.</Text><Text style={s.copy}>Será el espacio privado donde tu familia organiza colegio, actividades, estudio y pendientes cotidianos.</Text><TextInput style={s.input} placeholder="Ej. Familia Jara" placeholderTextColor="#A59687" value={familyName} onChangeText={setFamilyName} maxLength={100}/><TextInput style={s.input} placeholder="¿Cómo quieres aparecer tú?" placeholderTextColor="#A59687" value={displayName} onChangeText={setDisplayName} maxLength={100}/><Pressable style={[s.button,busy&&s.disabled]} disabled={busy} onPress={createFamily}><Text style={s.buttonText}>{busy?'Creando…':'Continuar'}</Text></Pressable></View>:
    <View style={s.card}><Text style={s.step}>PASO 2 DE 2</Text><Text style={s.title}>¿A quién vamos a acompañar?</Text><Text style={s.copy}>Puedes llamarle hijo, hija, niño, niña, estudiante o como ustedes prefieran. After usará siempre su nombre primero.</Text><TextInput style={s.input} placeholder="Nombre" placeholderTextColor="#A59687" value={firstName} onChangeText={setFirstName} maxLength={80}/><TextInput style={s.input} placeholder="Cómo le dicen en casa (opcional)" placeholderTextColor="#A59687" value={preferredName} onChangeText={setPreferredName} maxLength={80}/><Text style={s.label}>¿Cómo quieres referirte a esta persona?</Text><View style={s.chips}>{relationshipOptions.map(value=><Pressable key={value} onPress={()=>setRelationshipChoice(value)} style={[s.chip,relationshipChoice===value&&s.chipActive]}><Text style={[s.chipText,relationshipChoice===value&&s.chipTextActive]}>{value}</Text></Pressable>)}</View>{relationshipChoice==='Otro'?<TextInput style={s.input} placeholder="Ej. Sobrino, nieta, ahijado…" placeholderTextColor="#A59687" value={customRelationship} onChangeText={setCustomRelationship} maxLength={40}/>:null}<TextInput style={s.input} placeholder="Colegio (opcional)" placeholderTextColor="#A59687" value={schoolName} onChangeText={setSchoolName} maxLength={160}/><TextInput style={s.input} placeholder="Curso (opcional)" placeholderTextColor="#A59687" value={gradeLevel} onChangeText={setGradeLevel} maxLength={80}/><Pressable style={[s.button,busy&&s.disabled]} disabled={busy} onPress={createChild}><Text style={s.buttonText}>{busy?'Guardando…':'Entrar a After'}</Text></Pressable></View>}
  </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF8F1'},loading:{flex:1,alignItems:'center',justifyContent:'center',padding:24,gap:12},emoji:{fontSize:38},wrap:{paddingHorizontal:20,paddingTop:30,paddingBottom:44,gap:22},brandRow:{flexDirection:'row',alignItems:'center',gap:12},logo:{width:42,height:42,borderRadius:15,backgroundColor:'#F58B57',alignItems:'center',justifyContent:'center'},logoText:{color:'#FFF',fontSize:20,fontWeight:'900'},brand:{fontSize:17,fontWeight:'900',color:'#2B2926'},brandSub:{fontSize:12,color:'#817468',marginTop:2},card:{gap:14,backgroundColor:'#FFFDF9',borderWidth:1,borderColor:'#E8DDD1',borderRadius:24,padding:18},inviteBox:{backgroundColor:'#EAF4E5',borderRadius:22,padding:16,gap:12},inviteTitle:{fontSize:22,fontWeight:'900',color:'#30432F'},inviteRow:{flexDirection:'row',alignItems:'center',gap:12,borderTopWidth:1,borderTopColor:'#D5E5D0',paddingTop:12},inviteFamily:{fontSize:16,fontWeight:'900',color:'#30432F'},smallButton:{backgroundColor:'#6F8F68',borderRadius:12,paddingVertical:11,paddingHorizontal:16},step:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:'#9A7A60'},title:{fontSize:31,lineHeight:36,fontWeight:'900',letterSpacing:-.8,color:'#2B2926'},copy:{fontSize:15,lineHeight:22,color:'#6F655B'},label:{fontSize:13,fontWeight:'900',color:'#675C52',marginTop:2},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E8DDD1',borderRadius:16,padding:15,fontSize:16,color:'#2B2926'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingVertical:9,paddingHorizontal:12,borderRadius:999,borderWidth:1,borderColor:'#E6D8CA',backgroundColor:'#FFF'},chipActive:{backgroundColor:'#6F8F68',borderColor:'#6F8F68'},chipText:{fontSize:13,fontWeight:'800',color:'#6E6257'},chipTextActive:{color:'#FFF'},button:{backgroundColor:'#F58B57',borderRadius:16,padding:16,alignItems:'center',marginTop:3},buttonText:{color:'#FFF',fontSize:15,fontWeight:'900'},disabled:{opacity:.5}});